"""test1

Revision ID: 87eb3e290236
Revises: 79557408986d
Create Date: 2024-09-10 23:47:48.209252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87eb3e290236'
down_revision: Union[str, None] = '79557408986d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
